# Generated by Django 5.1.6 on 2025-02-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_hot_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
